/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_0$schema$value
const _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_0$schema = () => (_deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_1$schema$value
const _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_1$schema = () => (_deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_1$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_2$schema$value
const _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_2$schema = () => (_deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_2$schema$value ??= z.literal("continuable"))
let _deepseek_ai_dsh_subagent_subagents_interruptByParent_result$schema$value
const _deepseek_ai_dsh_subagent_subagents_interruptByParent_result$schema = () => (_deepseek_ai_dsh_subagent_subagents_interruptByParent_result$schema$value ??= z.object({
  'accepted': z.literal(true).readonly(),
}))
let _deepseek_ai_dsh_subagent_subagents_prompt_parameter_0$schema$value
const _deepseek_ai_dsh_subagent_subagents_prompt_parameter_0$schema = () => (_deepseek_ai_dsh_subagent_subagents_prompt_parameter_0$schema$value ??= z.object({
  'requestId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentSessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'childSessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'mode': z.literal("continuable").readonly(),
  'delivery': z.union([z.literal("queue"), z.literal("steer")]).readonly(),
  'content': z.array(z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'mediaType': z.union([z.literal("image/png"), z.literal("image/jpeg"), z.literal("image/webp"), z.literal("image/gif")]).readonly(),
  'data': z.string().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
})])).readonly(),
  'clientTimeZone': z.union([z.undefined(), z.string()]).readonly().optional(),
}))
let _deepseek_ai_dsh_subagent_subagents_prompt_result$schema$value
const _deepseek_ai_dsh_subagent_subagents_prompt_result$schema = () => (_deepseek_ai_dsh_subagent_subagents_prompt_result$schema$value ??= z.object({
  'messageId': z.intersection(z.string(), z.unknown()).readonly(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-subagent',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-subagent#subagents/interruptByParent',
      service: 'subagents',
      namespace: 'subagents',
      method: 'interruptByParent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'childSessionId',
          wire: 'childSessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-subagent#subagents/interruptByParent:childSessionId',
            create: _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_0$schema,
          },
        },
        {
          name: 'parentSessionId',
          wire: 'parentSessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-subagent#subagents/interruptByParent:parentSessionId',
            create: _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_1$schema,
          },
        },
        {
          name: 'mode',
          wire: 'mode',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-subagent#subagents/interruptByParent:mode',
            create: _deepseek_ai_dsh_subagent_subagents_interruptByParent_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-subagent/client#SubagentInterruptReceipt',
        create: _deepseek_ai_dsh_subagent_subagents_interruptByParent_result$schema,
      },
      sourceLocation: {"file":"packages/subagent/src/index.ts","line":490,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-subagent#subagents/prompt',
      service: 'subagents',
      namespace: 'subagents',
      method: 'prompt',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-subagent/client#SubagentPromptRequest',
            create: _deepseek_ai_dsh_subagent_subagents_prompt_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-subagent/client#SubagentPromptReceipt',
        create: _deepseek_ai_dsh_subagent_subagents_prompt_result$schema,
      },
      sourceLocation: {"file":"packages/subagent/src/index.ts","line":423,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Named provider registry with one-shot runs, durable discovery, and continuable-child operations.",
        "summary": "Named provider registry with one-shot runs, durable discovery, and continuable-child operations.",
        "tags": [],
        "jsDoc": "/** Named provider registry with one-shot runs, durable discovery, and continuable-child operations. */",
        "key": "subagents",
        "exportName": "SubagentRuntime",
        "members": [
          {
            "kind": "method",
            "name": "resolveMaxDepth",
            "signature": "resolveMaxDepth(configured?: number | 'provider-managed'): number | undefined",
            "summary": "Resolve a delegation tool's depth policy against the current user setting.",
            "jsDoc": "/**\n * Resolve a delegation tool's depth policy against the current user setting.\n * @param configured - Explicit tool limit, or provider-managed for external delegation.\n * @returns The numeric limit, or undefined when the provider owns depth enforcement.\n */"
          },
          {
            "kind": "method",
            "name": "startContinuable",
            "signature": "async startContinuable(spec: ContinuableStartSpec): Promise<ContinuableStart>",
            "summary": "Establish one durable continuable child and deliver its initial prompt.",
            "jsDoc": "/**\n * Establish one durable continuable child and deliver its initial prompt.\n * Resolves when the child's inbox accepts that prompt, without waiting for the\n * turn to start or for the message to reach the Session log; any earlier\n * failure rejects with no ids and rolls back the child entirely.\n * @param spec - provider, delegation request, and caller cancellation.\n * @returns the durable child id and the accepted prompt's message id.\n * @throws when continuation services are unavailable or materialization fails.\n */"
          },
          {
            "kind": "method",
            "name": "sendMessage",
            "signature": "async sendMessage( sender: Agent, targetId: SessionId, content: ContentBlock[], options: SubagentSendMessageOptions, ): Promise<MessageId>",
            "summary": "Steer one model-authored message to the sender's direct parent or direct continuable child.",
            "jsDoc": "/**\n * Steer one model-authored message to the sender's direct parent or direct\n * continuable child. A running target admits it at the nearest step boundary;\n * an idle target starts a turn, and an absent direct child cold-resumes from\n * persistence. The service derives durable sender attribution from the exact\n * live sender. Caller cancellation stops only pre-acceptance work.\n * @param sender - exact live Agent authorizing and originating the message.\n * @param targetId - durable direct-parent or direct-child session id.\n * @param content - model-authored content to deliver.\n * @param options - caller cancellation before inbox acceptance.\n * @returns the accepted message's inbox id.\n * @throws when continuation services are unavailable, adjacency is rejected,\n *   or the message was not admitted.\n */"
          },
          {
            "kind": "method",
            "name": "interrupt",
            "signature": "interrupt(targetSessionId: SessionId, authority: SubagentInterruptAuthority): void",
            "summary": "Interrupt one live continuable child's current turn under a human parent address or an exact live ancestor Agent.",
            "jsDoc": "/**\n * Interrupt one live continuable child's current turn under a human parent\n * address or an exact live ancestor Agent. Fire-and-return: the cancel\n * signal is issued before this returns, but the target may keep running\n * until it observes the signal. Unclaimed pending inbox work, the Activation,\n * and published descendants are preserved; claimed work is not requeued.\n * Once the interrupted driver is idle, a waking send resumes the parked FIFO\n * queue. An absent target — including a one-shot or unknown id —\n * is an accepted no-op, as is a manager-less composition, which cannot own a\n * live Activation.\n * @param targetSessionId - the durable child session id to interrupt.\n * @param authority - the human parent address or exact live ancestor Agent.\n * @throws {SubagentError} `UNAUTHORIZED` when the authority does not own the\n *   live target.\n */"
          },
          {
            "kind": "method",
            "name": "drainContinuableDescendants",
            "signature": "async drainContinuableDescendants(parents: readonly Agent[]): Promise<void>",
            "summary": "Close continuable admission below exact live parent Agents, stop only their visible descendant Activations synchronously, then await admitted scoped materializations and release those forests child-first.",
            "jsDoc": "/**\n * Close continuable admission below exact live parent Agents, stop only their\n * visible descendant Activations synchronously, then await admitted scoped\n * materializations and release those forests child-first. The scoped cutoff\n * lasts until each exact parent leaves the registry; unrelated parent trees\n * remain live.\n * @param parents - exact host-owned parent Agents entering teardown.\n * @returns once every retained descendant Activation released its `AgentHandle`.\n * @throws an aggregate error after all branches settle when any failed.\n */"
          },
          {
            "kind": "method",
            "name": "drainContinuableChildren",
            "signature": "async drainContinuableChildren(parent: Agent, childIds: readonly SessionId[]): Promise<void>",
            "summary": "Release selected resident continuable direct children of one exact live parent.",
            "jsDoc": "/**\n * Release selected resident continuable direct children of one exact live\n * parent. Other children of the same parent remain admitted and resident.\n * Absent targets and a manager-less composition are accepted no-ops.\n * @param parent - exact live direct parent authorizing the selected release.\n * @param childIds - durable direct-child ids to release when resident.\n * @returns once every selected Activation released its `AgentHandle`.\n * @throws {SubagentError} `UNAUTHORIZED` when a resident target belongs to a\n *   different parent or the supplied parent identity is stale.\n */"
          },
          {
            "kind": "method",
            "name": "listChildren",
            "signature": "listChildren(parentSessionId: SessionId, signal?: AbortSignal): Promise<SubagentCatalogEntry[]>",
            "summary": "Read the parent's durable direct-child catalog without loading or resuming an Agent.",
            "jsDoc": "/**\n * Read the parent's durable direct-child catalog without loading or resuming an Agent.\n * The service owns and releases the live-preferred Session observation.\n * @param parentSessionId - parent whose direct children are requested.\n * @param signal - cancellation forwarded to the Session query.\n * @returns catalog children in parent event order.\n * @throws {@link SubagentError} when query or catalog projection is unavailable.\n * @throws SessionQueryError when the parent cannot be read or the query is cancelled.\n */"
          },
          {
            "kind": "method",
            "name": "listDescendants",
            "signature": "listDescendants(rootSessionId: SessionId, signal?: AbortSignal): Promise<SubagentDescendantListEntry[]>",
            "summary": "Recursively list reachable parent catalogs in stable pre-order, preserving each catalog's event order.",
            "jsDoc": "/**\n * Recursively list reachable parent catalogs in stable pre-order, preserving\n * each catalog's event order. Each row carries its catalog parent and depth;\n * one-shot and unknown-mode children remain traversal nodes. Unknown modes\n * produce unsupported diagnostics. Unreadable child catalogs produce corrupt\n * or unavailable diagnostics and stop only that branch. Root read failures,\n * missing services or projections, and cancellation reject the whole listing.\n * Each catalog is observed once and released before the next read. No Agent\n * is loaded or resumed; Sessions absent from reachable catalogs are omitted.\n * @param rootSessionId - session whose catalog starts descendant discovery.\n * @param signal - cancellation forwarded to and checked around each catalog read.\n * @returns children and branch diagnostics in parent-catalog pre-order.\n * @throws {@link SubagentError} when listing dependencies are unavailable or the caller cancels.\n * @throws SessionQueryError when the root catalog cannot be read.\n */"
          },
          {
            "kind": "method",
            "name": "prompt",
            "signature": "@Remote('prompt') async prompt(request: SubagentPromptRequest, signal: AbortSignal): Promise<SubagentPromptReceipt>",
            "summary": "Deliver one browser-authored message to a continuable child through the exact live direct parent, retaining the caller-minted request identity and validated browser zone on the accepted message.",
            "jsDoc": "/**\n * Deliver one browser-authored message to a continuable child through the\n * exact live direct parent, retaining the caller-minted request identity and\n * validated browser zone on the accepted message. Success identifies the\n * message the child's inbox accepted; later execution is independent of this\n * call. Queue delivery targets a later turn; steer delivery targets the\n * nearest step and retains the Agent loop's best-effort fallback semantics.\n * Image parts are admitted and persisted through the attachment store\n * before delivery, and the child's model must accept image input.\n * Cold resume at capacity rejects with `subagent/delivery-unavailable`.\n * @param request - durable address, delivery, minted identity, content, and optional browser zone.\n * @param signal - carrier cancellation, owning the call until inbox acceptance.\n * @returns the accepted message's inbox identity.\n * @throws {RemoteError} `gateway/bad-request`, `subagent/attachment-invalid`,\n *   `subagent/invalid-time-zone`, `subagent/parent-unavailable`,\n *   `subagent/not-resumable`, `subagent/unauthorized`,\n *   `subagent/delivery-unavailable`, `gateway/cancelled`, or `gateway/internal`.\n */"
          },
          {
            "kind": "method",
            "name": "interruptByParent",
            "signature": "@Remote('interruptByParent') interruptByParent( childSessionId: SessionId, parentSessionId: SessionId, mode: 'continuable', ): SubagentInterruptReceipt",
            "summary": "Remote face of {@link interrupt} under one durable parent address.",
            "jsDoc": "/**\n * Remote face of {@link interrupt} under one durable parent address. No\n * catalog, history, persistence, or parent Agent lookup runs: the core\n * primitive alone authorizes the address against the live Activation, which\n * is what keeps a live child interruptible while its parent Agent is offline.\n * Absent, idle, and already-completed targets are accepted no-ops there.\n * @param childSessionId - durable child session id to interrupt.\n * @param parentSessionId - durable direct parent whose authority is claimed.\n * @param mode - required continuable-address discriminator.\n * @returns acknowledgement that the cancel signal was admitted, not that the target is quiescent.\n * @throws {RemoteError} `gateway/bad-request` for an empty id,\n *   `subagent/unauthorized` when the address does not own the live target,\n *   otherwise `gateway/internal`.\n */"
          },
          {
            "kind": "method",
            "name": "registerProvider",
            "signature": "registerProvider(provider: SubagentProvider): () => void",
            "summary": "Register a provider under its name.",
            "jsDoc": "/**\n * Register a provider under its name. Registration is effect-scoped and HMR\n * safe; removing a provider blocks new starts but does not revoke runs that\n * were already returned to their holders.\n * @param provider - the trusted provider implementation.\n * @returns the exact Cordis effect disposer.\n */"
          },
          {
            "kind": "method",
            "name": "getProvider",
            "signature": "getProvider(name: string): SubagentProvider | undefined",
            "summary": "Look up a provider by name.",
            "jsDoc": "/**\n * Look up a provider by name.\n * @param name - the provider name.\n * @returns the provider, or undefined when absent.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "list(): string[]",
            "summary": "List registered provider names in insertion order.",
            "jsDoc": "/**\n * List registered provider names in insertion order.\n * @returns the registered names.\n */"
          },
          {
            "kind": "method",
            "name": "start",
            "signature": "async start(name: string, request: SubagentStartRequest): Promise<SubagentRun>",
            "summary": "Establish a published child on the named provider.",
            "jsDoc": "/**\n * Establish a published child on the named provider. Capability and semantic\n * checks run before delegation. Provider ownership lasts until its promise\n * fulfills; a rejection therefore has no run for the caller to dispose and\n * emits no run lifecycle events. Post-publication turn and infrastructure\n * failures settle through the returned run.\n * A catalog append failure disposes the run and handles its result rejection;\n * the caller receives the catalog error even if disposal also fails.\n * @param name - the provider to use.\n * @param request - child label, prompt, parent, signal, and optional capabilities.\n * @returns the published holder-owned run.\n */"
          }
        ],
        "types": [
          {
            "name": "ContinuableCreateRequest",
            "declaration": "export interface ContinuableCreateRequest {\n    readonly sessionId: SessionId;\n    readonly parent: Agent;\n    readonly signal: AbortSignal;\n}"
          },
          {
            "name": "ContinuableCreateSpec",
            "declaration": "export interface ContinuableCreateSpec {\n    readonly seed?: readonly SessionEvent[];\n}"
          },
          {
            "name": "ContinuableStart",
            "declaration": "export interface ContinuableStart {\n    readonly childId: SessionId;\n    readonly messageId: MessageId;\n}"
          },
          {
            "name": "ContinuableStartSpec",
            "declaration": "export interface ContinuableStartSpec {\n    readonly provider: string;\n    readonly label: string;\n    readonly childId?: SessionId;\n    readonly request: Omit<SubagentStartRequest, 'label' | 'signal' | 'outputSchema'>;\n    readonly signal: AbortSignal;\n}"
          },
          {
            "name": "ContinuableSubagentDescriptorData",
            "declaration": "export interface ContinuableSubagentDescriptorData extends SubagentDescriptorBase {\n    readonly mode: 'continuable';\n    readonly label: string;\n    readonly agentProvider?: string;\n    readonly agentModel?: string;\n    readonly agentReasoningEffort?: ReasoningEffortId;\n    readonly persona?: string;\n    readonly toolFilter?: ToolRestriction;\n}"
          },
          {
            "name": "OneShotSubagentDescriptorData",
            "declaration": "export interface OneShotSubagentDescriptorData extends SubagentDescriptorBase {\n    readonly activation?: OwnedAuthorDialogActivationV1;\n    readonly rubyActivation?: OwnedRubyTaskActivationV1;\n    readonly mode: 'one-shot';\n    readonly label?: string;\n}"
          },
          {
            "name": "OwnedAuthorDialogActivationV1",
            "declaration": "export interface OwnedAuthorDialogActivationV1 {\n    readonly schemaVersion: 1;\n    readonly encoding: 'owned-author-dialog-v1';\n    readonly taskId: string;\n    readonly generation: string;\n    readonly promptPlanSha256: string;\n    readonly operationId: string;\n    readonly messageId: string;\n    readonly systemPrefix: string;\n    readonly dynamicSystem: string;\n}"
          },
          {
            "name": "OwnedRubyTaskActivationV1",
            "declaration": "export interface OwnedRubyTaskActivationV1 {\n    readonly schemaVersion: 1;\n    readonly encoding: 'owned-ruby-task-v1';\n    readonly taskId: string;\n    readonly generation: string;\n    readonly promptPlanSha256: string;\n    readonly userMessageId: string;\n    readonly orderedMessages: readonly OwnedRubyTaskMessageV1[];\n    readonly mainInputMessageIndex?: number;\n}"
          },
          {
            "name": "OwnedRubyTaskMessageV1",
            "declaration": "export interface OwnedRubyTaskMessageV1 {\n    readonly role: 'system' | 'user' | 'assistant';\n    readonly text: string;\n}"
          },
          {
            "name": "OwnedRubyTaskOwnerV1",
            "declaration": "export interface OwnedRubyTaskOwnerV1 {\n    readonly preparation: NativePreparationReceiptV1;\n    readonly snapshot: NativeRequestMaterialTransformV1['snapshot'];\n    readonly plan: NativeRequestMaterialTransformV1['plan'];\n    readonly captureSha256: string;\n    assertCurrent(): void;\n    readonly checkpoint: NativeInputAdmissionHookV2['checkpoint'];\n    readonly completedWork: NonNullable<NativeInputAdmissionHookV2['completedWork']>;\n    readonly onStop: NonNullable<NativeInputAdmissionHookV2['onStop']>;\n    readonly onBlocked?: NativeInputAdmissionHookV2['onBlocked'];\n}"
          },
          {
            "name": "ResolvedSubagentStartRequest",
            "declaration": "export interface ResolvedSubagentStartRequest extends SubagentStartRequest {\n    readonly descriptor: SubagentDescriptorData;\n}"
          },
          {
            "name": "SubagentCapabilities",
            "declaration": "export interface SubagentCapabilities {\n    readonly agentOptions: boolean;\n    readonly outputSchema: boolean;\n    readonly depthLimit: boolean;\n    readonly toolFilter: boolean;\n    readonly persona: boolean;\n    readonly ownedAuthorDialog?: boolean;\n    readonly ownedRubyTask?: boolean;\n}"
          },
          {
            "name": "SubagentCatalogEntry",
            "declaration": "export type SubagentCatalogEntry = { readonly id: SessionId; readonly createdAt: number; } & ({ readonly mode: 'one-shot'; readonly label?: string; } | { readonly mode: 'continuable'; readonly label: string; } | { readonly mode: 'unknown'; readonly label?: string; });"
          },
          {
            "name": "SubagentCatalogRow",
            "declaration": "export type SubagentCatalogRow = { readonly id: SessionId; readonly activity: 'running' | 'inactive'; } & ({ readonly mode: 'one-shot'; readonly label?: string; } | { readonly mode: 'continuable'; readonly label: string; });"
          },
          {
            "name": "SubagentDescendantListEntry",
            "declaration": "export type SubagentDescendantListEntry = SubagentListEntry & { readonly parentId: SessionId; readonly depth: number; };"
          },
          {
            "name": "SubagentDescriptorBase",
            "declaration": "export interface SubagentDescriptorBase {\n    readonly version: number;\n    readonly mode: 'one-shot' | 'continuable';\n    readonly provider: string;\n}"
          },
          {
            "name": "SubagentDescriptorData",
            "declaration": "export type SubagentDescriptorData = OneShotSubagentDescriptorData | ContinuableSubagentDescriptorData;"
          },
          {
            "name": "SubagentInterruptAuthority",
            "declaration": "export type SubagentInterruptAuthority = { readonly kind: 'user'; readonly parentSessionId: SessionId; } | { readonly kind: 'ancestor'; readonly agent: Agent; };"
          },
          {
            "name": "SubagentInterruptReceipt",
            "declaration": "export interface SubagentInterruptReceipt {\n    readonly accepted: true;\n}"
          },
          {
            "name": "SubagentListEntry",
            "declaration": "export type SubagentListEntry = SubagentCatalogRow & { readonly kind: 'child'; readonly hasChildren: boolean; } | { readonly kind: 'diagnostic'; readonly id: SessionId; readonly reason: 'corrupt' | 'unsupported' | 'unavailable'; };"
          },
          {
            "name": "SubagentPromptReceipt",
            "declaration": "export interface SubagentPromptReceipt {\n    readonly messageId: MessageId;\n}"
          },
          {
            "name": "SubagentPromptRequest",
            "declaration": "export interface SubagentPromptRequest {\n    readonly requestId: SubagentPromptRequestId;\n    readonly parentSessionId: SessionId;\n    readonly childSessionId: SessionId;\n    readonly mode: 'continuable';\n    readonly delivery: 'queue' | 'steer';\n    readonly content: readonly PromptContentPart[];\n    readonly clientTimeZone?: string;\n}"
          },
          {
            "name": "SubagentPromptRequestId",
            "declaration": "export type SubagentPromptRequestId = Branded<'session-request-id'>;"
          },
          {
            "name": "SubagentProvider",
            "declaration": "export interface SubagentProvider {\n    readonly name: string;\n    readonly capabilities: SubagentCapabilities;\n    readonly inheritsParentContext: boolean;\n    readonly agentRouteDefaults?: Readonly<{ provider: string; model: string; }>;\n    start(request: ResolvedSubagentStartRequest): Promise<SubagentRun>;\n    prepareContinuable?(request: ContinuableCreateRequest): Promise<ContinuableCreateSpec>;\n}"
          },
          {
            "name": "SubagentResult",
            "declaration": "export interface SubagentResult {\n    readonly output: readonly ContentBlock[];\n    readonly structured?: unknown;\n    readonly diagnostic?: string;\n    readonly stopReason: SubagentStopReason;\n}"
          },
          {
            "name": "SubagentRun",
            "declaration": "export interface SubagentRun {\n    readonly id: SessionId;\n    readonly localAgent: Agent | undefined;\n    readonly result: Promise<SubagentResult>;\n    dispose(): Promise<void>;\n}"
          },
          {
            "name": "SubagentSendMessageOptions",
            "declaration": "export interface SubagentSendMessageOptions {\n    readonly signal: AbortSignal;\n}"
          },
          {
            "name": "SubagentStartRequest",
            "declaration": "export interface SubagentStartRequest {\n    readonly activation?: OwnedAuthorDialogActivationV1;\n    readonly rubyActivation?: OwnedRubyTaskActivationV1;\n    readonly rubyOwner?: OwnedRubyTaskOwnerV1;\n    readonly label?: string;\n    readonly prompt: ContentBlock[];\n    readonly parent: Agent;\n    readonly signal: AbortSignal;\n    readonly agentOptions?: AgentOptions;\n    readonly outputSchema?: ObjectJsonSchema;\n    readonly maxDepth?: number;\n    readonly toolFilter?: ToolRestriction;\n    readonly persona?: string;\n}"
          },
          {
            "name": "SubagentStopReason",
            "declaration": "export type SubagentStopReason = SubagentStopReasonMap[keyof SubagentStopReasonMap];"
          },
          {
            "name": "SubagentStopReasonMap",
            "declaration": "export interface SubagentStopReasonMap {\n    completed: 'completed';\n    aborted: 'aborted';\n    error: 'error';\n    'max-tokens': 'max-tokens';\n    refusal: 'refusal';\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "A published child settled. Scope-filtered dispatch uses the same delegating parent carrier as `subagent/start`, so the lifecycle pair reaches the same scoped audience.",
        "summary": "A published child settled.",
        "tags": [
          {
            "name": "param",
            "argument": "info",
            "comment": "- the run identity and terminal outcome.",
            "text": "@param info - the run identity and terminal outcome.\n     *"
          },
          {
            "name": "dshScopeScan",
            "comment": "unsupported",
            "text": "@dshScopeScan unsupported\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A published child settled. Scope-filtered dispatch uses the same delegating\n * parent carrier as `subagent/start`, so the lifecycle pair reaches the\n * same scoped audience.\n * @param info - the run identity and terminal outcome.\n * @dshScopeScan unsupported\n * @mode emit\n */",
        "name": "subagent/end",
        "mode": "emit",
        "signature": "'subagent/end'(this: Scoped<SubagentRuntime>, info: SubagentRunEndInfo): void"
      },
      {
        "description": "A provider became resolvable in the registry.",
        "summary": "A provider became resolvable in the registry.",
        "tags": [
          {
            "name": "param",
            "argument": "provider",
            "comment": "- the registered provider.",
            "text": "@param provider - the registered provider.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A provider became resolvable in the registry.\n * @param provider - the registered provider.\n * @mode emit\n */",
        "name": "subagent/provider-added",
        "mode": "emit",
        "signature": "'subagent/provider-added'(provider: SubagentProvider): void"
      },
      {
        "description": "A provider left the registry. Accepted runs remain holder-owned.",
        "summary": "A provider left the registry.",
        "tags": [
          {
            "name": "param",
            "argument": "name",
            "comment": "- the provider name that no longer resolves.",
            "text": "@param name - the provider name that no longer resolves.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A provider left the registry. Accepted runs remain holder-owned.\n * @param name - the provider name that no longer resolves.\n * @mode emit\n */",
        "name": "subagent/provider-removed",
        "mode": "emit",
        "signature": "'subagent/provider-removed'(name: string): void"
      },
      {
        "description": "A provider established a published child. For in-process providers, `ctx.agents.get(info.id)` resolves during this notification. Scope-filtered dispatch keys the carrier by the delegating parent, so a parent-scoped listener observes only its own delegations. Paired with `subagent/end`.",
        "summary": "A provider established a published child.",
        "tags": [
          {
            "name": "param",
            "argument": "info",
            "comment": "- the provider and published child identity.",
            "text": "@param info - the provider and published child identity.\n     *"
          },
          {
            "name": "dshScopeScan",
            "comment": "unsupported",
            "text": "@dshScopeScan unsupported\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A provider established a published child. For in-process providers,\n * `ctx.agents.get(info.id)` resolves during this notification.\n * Scope-filtered dispatch keys the carrier by the delegating parent, so a\n * parent-scoped listener observes only its own delegations. Paired with\n * `subagent/end`.\n * @param info - the provider and published child identity.\n * @dshScopeScan unsupported\n * @mode emit\n */",
        "name": "subagent/start",
        "mode": "emit",
        "signature": "'subagent/start'(this: Scoped<SubagentRuntime>, info: SubagentRunInfo): void"
      }
    ],
    "objects": []
  },
}
